//
//	DO NOT EDIT : This file was automatically generated by the Access database 'DSA3000 Parameter Definition.mdb'
//
//
//This file contains all of the parameter code definitions for this application
//NOTE: This file is used on both C++ compilations along with MIDL compilations
//		Therefore, be aware of what gets put in here so both compilers are able
//		to compile this file without error or warnings
//

#ifndef __EXPOSE_TO_MIDL
#pragma once
namespace Canberra {
	namespace DataTypes {
		namespace Lynx {

			//
			//This enumeration is used to define all possible
			//DSA parameter types that are used for configuring
			//the instrument
			//
			namespace ParameterCodes
			{
#endif


#ifndef __EXPOSE_TO_MIDL
				typedef enum CodeTag
				{
#else
				typedef enum ParameterCodeTag {
#endif
					System_MaxParameterCode=329, // Last Parameter code
					Security_DigitalSignatures=6,		// (0)	Enable digital signaturing
					Input_SeedSpectrum=7,		//			Name of a CAM file for seeding the input for simulation
					Input_SeedVariate=8,		// (10.0)	A multiplier for the random variate used for simulation
					Simulator_Enable=9,		// (0)	Enables the simulator
					UPnP_FriendlyName=10,		// (Lynx)	The UPnP device name (displayed in user's WinXP network folder)
					Time_TimeZone=11,		// (Eastern Standard Time)	The time zone.  Valid time zones are contained in set: {"Dateline Standard Time~Samoa Standard Time~Hawaiian Standard Time~Alaskan Standard Time~Pacific Standard Time~Mountain Standard Time~Mexico Standard Time 2~US Mountain Standard Time~Central Standard Time~Canada Central Standard Time~Mexico Standard Time~Central America Standard Time~Eastern Standard Time~US Eastern Standard Time~SA Pacific Standard Time~Atlantic Standard Time~SA Western Standard Time~Pacific SA Standard Time~Newfoundland Standard Time~E. South America Standard Time~SA Eastern Standard Time~Greenland Standard Time~Mid-Atlantic Standard Time~Azores Standard Time~Cape Verde Standard Time~GMT Standard Time~Greenwich Standard Time~Central Europe Standard Time~Central European Standard Time~Romance Standard Time~W. Europe Standard Time~W. Central Africa Standard Time~E. Europe Standard Time~Egypt Standard Time~FLE Standard Time~GTB Standard Time~Jerusalem Standard Time~South Africa Standard Time~Russian Standard Time~Arab Standard Time~E. Africa Standard Time~Arabic Standard Time~Iran Standard Time~Arabian Standard Time~Caucasus Standard Time~Afghanistan Standard Time~Ekaterinburg Standard Time~West Asia Standard Time~India Standard Time~Nepal Standard Time~Central Asia Standard Time~Sri Lanka Standard Time~N. Central Asia Standard Time~Myanmar Standard Time~SE Asia Standard Time~North Asia Standard Time~China Standard Time~Malay Peninsula Standard Time~Taipei Standard Time~W. Australia Standard Time~North Asia East Standard Time~Korea Standard Time~Tokyo Standard Time~Yakutsk Standard Time~AUS Central Standard Time~Cen. Australia Standard Time~AUS Eastern Standard Time~E. Australia Standard Time~Tasmania Standard Time~Vladivostok Standard Time~West Pacific Standard Time~Central Pacific Standard Time~Fiji Standard Time~New Zealand Standard Time~Tonga Standard Time"}
					Time_CorrectForDaylightSavings=12,		// (1)	Daylight savings time correction enable/disable
					Network_IPAddress=13,		// (10.0.0.3)	Static IP address for the preferred adapter
					Network_EnableDHCP=14,		// (0)	Enable/disable DHCP for the device
					Network_Gateway=15,		//			Default gateway address
					Network_Subnet=16,		// (255.255.255.0)	Subnet address
					Network_DNSAddress=17,		//			DNS address
					Network_DNSAlternateAddress=18,		//			DNS alternate address
					Network_WINSAddress=19,		//			WINS address
					Network_WINSAlternateAddress=20,		//			WINS alternate address
					Network_RAS_Enable=21,		// (1)	Serial port configuration mode.  See RASenableLine enumeration
					Network_RAS_User=22,		// (user)	User name for serial port communications
					Network_RAS_Password=23,		// (7821511937721f3739da2ec223b5b5546f292c389eb503be)	Password for serial port communications
					Network_RAS_Subnet=24,		// (255.255.255.0)	Subnet address for serial port communications
					Network_RAS_IPAddress=25,		// (10.0.0.1)	IP address for communication over serial port
					Configuration_MaximumNumberOfClients=26,		// (10)	The maximum number of simultaneous network clients for configuring the device
					Network_TimeSynchronization_Enable=27,		// (1)	Enables time synchronization services
					Network_TimeSynchronization_ServerAddress=28,		// (132.163.4.101)	The address of the time sync server
					Network_TimeSynchronization_RefreshRate=29,		// (300000)	The time sync server refresh rate (ms)
					Network_TimeSynchronization_Threshold=30,		// (600000)	The time sync server threshold (ms)
					Network_TimeSynchronization_RecoveryRefreshRate=31,		// (300000)	The recovery refresh rate (ms)
					System_StorageLimit=32,		// (10)	The storage limit in %.  This when the system gets below this number a fault is annunciated
					AuditManager_Storage_MaxSize=33,		// (90000)	The maximum file size in bytes for the audit log
					AuditManager_Enable=34,		// (1)	Enable the auditing
					Localization_LCID=35,		// (1033)	Localization locale
					Watchdog_Enable=36,		// (1)	The watchdog enable state
					Watchdog_TimeOut=37,		// (600000)	The watchdog time out (ms)
					Preset_Options=38,		// (0)	The preset options.  See PresetOptions enumeration
					Preset_Live=39,		// (1000.0)	The preset live limit
					Preset_Real=40,		// (1000.0)	The preset real limit
					Preset_StartChan=41,		// (1)	Computational preset start channel
					Preset_EndChan=42,		// (20)	Computational preset end channel
					Input_Name=43,		//			The input name
					Input_Owner=44,		//			The input's owner . Returns an XML document containing all the information about the current owner.
					Input_LockState=45,		//			The lock state (0=Not locked, 1=Locked)
					Input_NumberOfGroups=46,		// (1)	Number of memory groups
					Input_CurrentGroup=47,		// (1)	The current memory group in use
					System_NumberOfInputs=48,		//			The number of inputs the device has
					Calibrations_Energy_Offset=49,		// (0.0)	The energy calibration offset
					Calibrations_Energy_Slope=50,		// (0.5)	The energy calibration slope
					Calibrations_Energy_Quad=51,		// (0.0)	The energy calibration quadratic
					Calibrations_FWHM_SquareRoot_Offset=52,		// (1.0)	The shape square root model offset
					Calibrations_FWHM_SquareRoot_Slope=53,		// (0.03)	The shape square root model slope
					Calibrations_FWHM_Poly_Offset=54,		// (0.0)	The shape poly model offset
					Calibrations_FWHM_Poly_Slope=55,		// (0.0)	The shape poly model slope
					Calibrations_FWHM_Poly_Quad=56,		// (0.0)	The shape poly model quad
					Calibrations_FWHM_CurrentModel=57,		// (0)	The shape current model in use see FwhmModelType enumeration
					Calibrations_LowTail_Poly_Offset=58,		// (0.0)	The low tail poly model offset
					Calibrations_LowTail_Poly_Slope=59,		// (0.0)	The low tail poly model slope
					Input_Mode=60,		// (0)	The acquisition mode of the input
					Input_Status=61,		//			The status of the input.  See StatusBit enumeration
					Preset_Totals=62,		// (10)	The preset total counts
					Preset_Sweeps=63,		// (1)	The preset sweeps
					Elapsed_Totals=64,		// (0)	The elapsed total counts
					Elapsed_Sweeps=65,		// (0)	The elapsed sweeps
					Elapsed_Live=66,		// (0)	The elapsed live. Units are uSec
					Elapsed_Real=67,		// (0)	The elapsed real.  Units are uSec
					Input_StartTime=69,		//			The acquisition start time. The units are the number of 100-nanosecond intervals since January 1, 1601.
					Input_NumberOfChannels=70,		// (4096)	The number of channels/conversion gain
					Input_Capabilities=71,		// (1)	The capabilities of the hardware
					Input_RoiUncMult=72,		// (1.0)	Uncertainty multiplier for display ROI quantifications
					Input_RoiNumBkgChans=73,		// (2)	Number of background channels for display ROI quantifications
					Network_RNDIS_EnableDHCP=75,		// (0)	Enable DHCP for RNDIS (PPP over USB)
					Network_RNDIS_Gateway=76,		//			Default gateway for RNDIS (PPP over USB)
					Network_RNDIS_Subnet=77,		// (255.255.255.0)	Subnet mask for RNDIS (PPP over USB)
					Network_RNDIS_IPAddress=78,		// (10.0.0.2)	Static IP for RNDIS (PPP over USB)
					Webserver_LoginEnabled=79,		// (0)	The login required state for website
					System_SerialNumber=80,		// ((none available))	The device serial number
					Network_MachineName=81,		// (Lynx)	The name used name resolution on a network with WINS enabled
					System_DateTime=82,		//			The system date/time. The units are the number of 100-nanosecond intervals since January 1, 1601.
					UPnP_TimeToLive=83,		// (3)	UPnP Time To Live.  The number of routers the UPnP messages can go through
					UPnP_Enable=84,		// (1)	UPnP Enable state
					Webserver_Enable=86,		// (1)	Enable the web server
					Webserver_MaximumNumberOfClients=87,		// (20)	The maximum number of connections to the web server
					Configuration_Port=91,		// (16385)	The network port for configuring the instrument
					Configuration_SessionTimeout=92,		// (600000)	The session timeout for stale network configuration client connections (ms)
					DSO_CaptureInterval=94,		// (100)	The DSO capture interval (in 12.5 nSec units at which data is captured)
					DSO_SampleRate=95,		// (100)	The DSO sampling rate nSec
					DSO_TriggerLevel=96,		// (100)	The DSO trigger level
					DSO_NumberOfPreTriggerSamples=97,		// (10)	The DSO number of pretrigger samples in 12.5 nSec units
					DSO_NumberOfPostTriggerSamples=98,		// (10)	The DSO number of posttrigger samples
					DSO_TriggerSource=99,		// (10)	The DSO trigger source
					DSO_TriggerSlope=100,		// (0)	The DSO trigger slope (0 - 2)
					DSO_Simulate=101,		// (0)	The DSO simulator enable state
					DSO_Variate=102,		// (10)	The DSO simulator variate multiplier
					DSO_NumberOfAnalogSignals=103,		// (5)	The DSO number of analog signals
					DSO_NumberOfDigitalSignals=104,		// (5)	The DSO number of digital signals
					DSO_EnableCapture=105,		// (0)	The DSO enables the capture of DSO data
					UPnP_DeviceType=106,		// (urn:schemas-upnp-org:device:Basic:1)	UPnP Device Type in URN form
					UPnP_ModelDescription=107,		// (Digital Multichannel Analyzer)	Null
					UPnP_ModelName=108,		// (Lynx)	Null
					UPnP_ModelNumber=109,		// (1)	Null
					UPnP_ModelSerialNumber=110,		// (0001)	Null
					UPnP_ServiceType=111,		// (urn:schemas-upnp-org:service:radiationSensor:1)	Null
					UPnP_ServiceID=112,		// (urn:schemas-upnp-org:service:radiationSensor)	Null
					UPnP_PresentationURL=113,		// (default.html)	Null
					UPnP_MajorVersion=114,		// (1)	Null
					UPnP_MinorVersion=115,		// (0)	Null
					UPnP_UPC=116,		// (00000-00001)	Null
					UPnP_UDN=117,		//			Null
					Network_EnableRouting=119,		// (1)	Enable network routing.
					Network_RAS_BaudRate=120,		// (57600)	Serial port Baud Rate (default is 57600)
					Network_FTP_Enable=123,		// (0)	FTP server enable state
					Network_FTP_UserList=124,		//			User list for FTP server
					Network_FTP_DefaultDir=125,		// (\NAND_Flash)	Default directory for FTP server
					Network_FTP_UseAuthentication=126,		// (0)	Require authentication with FTP server
					Network_FTP_AllowAnonymousUpload=127,		// (1)	Allow anonymous file uploads to FTP server
					System_RebootTimeOut=136,		// (60000)	Time till actual reboot occurs after reboot command issued (mS)
					System_MemoryLimit=137,		// (10.0)	The upper RAM memory limit for fault monitoring.  When RAM exceeds this percentage value the system generates a fault
					System_StorageTimeLimit=138,		// (60.0)	Time till temporary files are deleted (s)
					Input_DisplayRois_Start=139,		//			An array of the Start values for a series of ROIs.  No default values
					Input_DisplayRois_End=140,		//			An array of the End values for a series of ROIs.  No default values
					Input_DisplayRois_Type=141,		//			An array of the Type values for a serioes of ROIs.  No default values
					Security_UserNames=142,		//			An array of user names
					Security_Passwords=143,		//			An array of passwords stored as hexidecimal strings
					Input_FineGain=145,		// (1.0)	Fine gain setting
					Network_Wireless_IPAddress=146,		//			IP Address for the wireless network adapter
					Network_Wireless_EnableDHCP=147,		// (1)	Set to true to use DHCP to obtain wireless IP address
					Network_Wireless_Gateway=148,		//			IP Address of the gateway used by the wireless network adapter
					Network_Wireless_Subnet=149,		// (255.255.255.0)	Subnet mask to use for the wireless network
					Network_Wireless_DNSAddress=150,		//			First DNS Address used by the wireless network
					Network_Wireless_DNSAlternateAddress=151,		//			Alternate DNS address used by the wireless network
					Network_Wireless_WINSAddress=152,		//			Address for WINS name resolution by the wireless network
					Network_Wireless_WINSAlternateAddress=153,		//			Alternate address for WINS name resolution by the wireless network
					Input_CoarseGain=154,		// (4.0)	Coarse gain setting
					Input_Attenuate=155,		// (0)	Input attenuator (true=multiply by .25, false=multiply by 1)
					Input_PoleZero=157,		// (2048)	Pole zero DAC setting
					Input_Voltage=158,		// (0)	Voltage Setting (V)
					Input_VoltageRange=159,		// (1500)	Voltage Range (V)
					Input_VoltagePolarity=160,		// (0)	Voltage Polarity, 0 positive, 1 negative
					Input_VoltageStatus=161,		// (0)	Voltage Status setting, 0 off, 1 on
					Input_VoltageInhibitControl=162,		// (0)	Voltage Inhibit Control. See OnOff enumeration
					Input_VoltageInhibitPolarity=163,		// (0)	Voltage Inhibit Polarity.  See Polarity enumeration
					Input_VoltageRamping=164,		//			Voltage Ramping, 0 normal, 1 ramping
					Input_VoltageFault=165,		//			Voltage Fault (or inhibit) 0 normal, 1 fault
					Input_VoltageReading=166,		//			Measured voltage (V)
					Input_VoltageLimit=167,		// (1500)	Voltage Range Limit  (V)
					Input_VoltageState=169,		//			Real time voltage state (only off when done ramping)
					Input_Spectrum=170,		//			Spectral data (unsigned long buffer, special handling)
					DSO_NumberOfSweeps2Avg=171,		// (10)	The number of sweeps to average
					DSO_TriggerMode=172,		// (0)	The trigger mode
					System_ResetButtonPressed=173,		//			The button was pressed to reset settings
					DSO_Flags=174,		// (0)	The DSO flags (0=pileup reject events)
					DSO_AnalogSignalsMask=175,		// (0)	The analog signals to view (bitmask)
					Security_UserDescriptions=176,		//			A description of the user
					Security_UserPrivileges=177,		//			Bitmask of the user privileges
					System_Rebooting=178,		//			The rebooting state of the device
					Network_Wireless_SSID=179,		//			The SSID of the access point
					Network_Wireless_InfrastructureMode=180,		// (1)	Type of connection (0=connect wireless computer to wireless computer, 1=connect to wireless ACP)
					Network_Wireless_Encryption=181,		// (1)	Encryption method (0=WEP enabled, 1=WEP disabled, 4=TKIP enabled)
					Network_Wireless_Authentication=182,		// (0)	Authentication method (0=Open, 1=Shared, 3=WPA, 4=WPAPSK, 5=WPANone)
					Network_Wireless_Key=183,		//			Privacy key
					Network_Wireless_KeyIndex=184,		// (1)	The privacy key index
					Network_Wireless_KeyAuto=185,		// (1)	Key is automatically provided
					Network_Wireless_EapType=186,		// (4)	Extended Authentication Protocol type (4=MD5, 13=TLS, 25=PEAP)
					Input_Dwell=187,		// (.001)	MCS dwell time (sec)
					DSO_TriggerStatus=188,		//			Current trigger status of DSO
					DSO_DataAvailable=189,		//			New data available for the digital oscilloscope
					DSO_ExcessivePileup=190,		//			Excessive Pile Up in the digital oscilloscope
					DSO_SampleCount=191,		//			Number of samples available in the DSO capture buffer
					DSO_Capture=192,		//			DSO Capture data (unsigned long buffer, special handling)
					Input_FilterMode=193,		// (0)	Input filter mode (0 triangular shaper, 1-15 reserved, 16 pole zero)
					Input_SlowRiseTime=194,		// (5.6)	Filter slow rise time (uS)
					Input_SlowFlatTop=195,		// (.8)	Filter slow flat top  (uS)
					Input_PoleZeroError=200,		//			Pole zero status.  See AutoPoleZeroStatusBits enumeration
					System_AppBasePath=202,		//			The path of application root directory
					System_FirmwareVersion=203,		//			The firmware version
					DSO_Resolution=204,		//			The DSO time resolution in nSec (ex. 12.5)
					Input_DiscMode=205,		// (0)	The discriminator mode.  See McsDiscModes enumeration
					Input_DiscROIStart=206,		// (1)	The ROI start channel when device has discriminator mode=ROI
					Input_DiscROIEnd=207,		// (20)	The ROI end channel when device has discriminator mode=ROI
					Counter_GateTimer=208,		// (0)	Auxiliary counters gate timer for counters (uS)
					Counter_TestPulser=210,		// (0)	Enable/disable GPIO3 to route signals to auxilary counters for test pulser purposes.  See OnOff enumeration
					Counter_ExternalSyncMode=211,		// (0)	Auxiliary counters external synchronization mode.   See ClockSource enumeration
					Counter_AcquisitionInterval=212,		// (100)	Auxiliary counters sampling rate (ms)
					Counter_Mode=213,		// (0)	Auxiliary counters mode.  See AutomaticManual enumeration
					Input_CoincGateMode=215,		// (0)	Coincidence gate mode.  See CoincGateMode enumeration
					Input_CoincGatePolarity=216,		// (0)	Coincidence polarity.  See Polarity enumeration
					Input_CoincGateDelay=217,		// (0)	Coincidence gate delay (uS)
					Input_StabilizerGainCorrRange=218,		// (0)	Stabilizer gain correction range.  See StabilizerCorrectionRange enumeration
					Input_StabilizerGainMode=219,		// (0)	Stabilizer gain mode.  See StabilizerMode enumeration
					Input_StabilizerGainStatus=220,		// (0)	Stabilizer gain status
					Input_StabilizerCorrDivider=221,		// (0)	Stabilizer correction divider
					Input_StabilizerSpacing=222,		// (10)	Stabilizer spacing
					Input_StabilizerWindow=223,		// (4)	Stabilizer window
					Input_StabilizerRatioMode=224,		// (1)	Stabilizer ratio mode.  See AutomaticManual enumeration
					Input_StabilizerCorrectionValue=225,		// (1.0)	Stabilizer correction value
					Input_StabilizerManualRatio=226,		// (1.0)	Stabilizer manual ratio
					Input_StabilizerCentroid=227,		// (10)	Stabilizer centroid
					Input_McsExternalControlMode=228,		// (0)	MCS external start/stop mode.  See ExternalControlMode enumeration
					Input_McsExternalControlPolarity=229,		// (0)	Polarity of MCS external control signal. See Polarity enumeration
					Input_McsExternalControl=230,		// (2)	MCS external start/stop control.  See ExternalControl enumeration
					Input_DigitalOffset=231,		// (0)	Digital offset
					Input_PhaExternalControlMode=232,		// (0)	PHA external start/stop mode.  See ExternalControlMode enumeration
					Input_PhaExternalControlPolarity=233,		// (0)	Polarity of PHA external control signal. See Polarity enumeration
					Input_PhaExternalControl=234,		// (2)	PHA external start/stop control. See ExternalControl enumeration
					Input_BLRmode=235,		// (0)	Base-line restore mode.  See BLRmode enumeration
					Input_PreampType=236,		// (0)	Preamp type.  See PreampType enumeration
					Input_FastDiscShaping=237,		// (0)	Fast discriminator shaping mode.  See FDiscShaping enumeration
					Input_FastDiscMode=238,		// (0)	Fast discriminator mode.  See AutomaticManual enumeration
					Input_FastDisc=239,		// (1)	Fast discriminator manual setting %
					Input_LLDmode=240,		// (0)	Lower level discriminator mode. See AutomaticManual enumeration
					Input_LLD=241,		// (.1)	Lower level discriminator manual setting %
					Input_ULD=242,		// (100)	Upper level discriminator setting %
					Input_PURguard=243,		// (11)	PUR guard
					Input_LTtrim=244,		// (500)	LT trim
					Input_PURLTCmode=245,		// (1)	PUR/LTC mode.  See OnOff enumeration
					Input_Polarity=246,		// (0)	Input polarity. See Polarity enumeration
					Input_Countrate=247,		// (0.0)	Input count rate (cps)
					Input_TRPInhibitmode=248,		// (0)	TRP inhibit mode. See AutomaticManual enumeration
					Input_TRPInhibit=249,		// (10)	TRP inhibit manual setting (uS)
					Input_TRPGatepolarity=250,		// (0)	TRP gate polarity. See Polarity enumeration
					Input_ChangerAdvPolarity=251,		// (0)	Sample changer advance polarity.  See Polarity enumeration
					Input_ChangerReadyPolarity=252,		// (0)	Sample changer ready polarity.  See Polarity enumeration
					Counter_Status=253,		// (0)	Auxiliary counters status. See CounterStatus enumeration.  Write to this parameter to start/stop data acquisition.  Read this parameter to get current acquisition status
					GPIO1_Control=254,		// (0)	Mode for GPIO 1. See GPIOcontrolCodes enumeration
					GPIO2_Control=255,		// (0)	Mode for GPIO 2 . See GPIOcontrolCodes enumeration
					GPIO3_Control=256,		// (0)	Mode for GPIO 3.See GPIOcontrolCodes enumeration
					GPIO4_Control=257,		// (0)	Mode for GPIO 4.See GPIOcontrolCodes enumeration
					GPIO1_Input=258,		//			State for GPIO1
					GPIO2_Input=259,		//			State for GPIO2
					GPIO3_Input=260,		//			State for GPIO3
					GPIO4_Input=261,		//			State for GPIO4
					Input_ExternalSyncStatus=263,		// (0)	Enable/disable external sync.  See ExternalSyncStatus enumeration
					Input_ExternalSyncMode=264,		// (0)	External sync mode.  See ExternalSyncMode enumeration
					Input_ExternalSyncPulse=265,		// (1000)	External sync pulse (mS)
					Input_ExternalSyncTimeO=266,		// (2000)	External sync timeout (mS)
					Input_ExternalSyncPolarity=267,		// (0)	External sync polarity. See Polarity enumeration
					Network_WirelessBoundAddress=268,		// (0.0.0.0)	The  bound address of the wireless network card
					Network_WiredBoundAddress=269,		// (0.0.0.0)	The bound address of the wired network card
					Input_ChangerReady=270,		// (0)	The changer ready state (0=not ready, 1=ready)
					Input_Deadtime=271,		// (0.0)	The deadtime %
					Input_RWregister=272,		//			Read/write register
					Network_RAS_ModemCmdSndDelay=273,		// (200)	The number of milliseconds to delay sending the modem a command
					Input_McsExternalChanAdvMode=274,		// (0)	MCS external channel advance mode.  See OnOff enumeration
					Input_McsExternalChanAdvPolarity=275,		// (0)	MCS external channel advance polarity.  See Polarity enumeration
					Input_McsExternalSweepAdvMode=276,		// (0)	MCS external sweep advance mode.  See OnOff enumeration
					Input_McsExternalSweepAdvPolarity=277,		// (0)	MCS external sweep polarity. See Polarity enumeration
					Input_MonitorControl=278,		// (1)	Monitor output control.  See MonitorOutControl enumeration
					Security_UserTypes=280,		//			Type of security account (0=any, 1=Anonymous, 2=Admin)
					System_DiagnosticsOptions=281,		// (7)	Diagnostic options.  See DiagnosticOptions enumeration
					Input_ListMode=282,		// (0)	The operational mode for list mode
					Input_ListBufferSize=284,		// (10000)	The buffer size
					System_DiagnosticsEnableOptions=286,		// (0)	Enable options.  See DiagnosticEnableOptions  enumeration
					Input_Fault=287,		// (0)	Fault bits for the specific input
					Input_LastError=288,		//			Localized string containing the last error/fault message
					Input_AutoPoleZeroValue=289,		//			DAC Value determined by automatic pole zero algorithm
					System_StorageSettings=290,		// (0)	Flags for storing parameters (1=Write Network Settings to Nor)
					Input_ElapsedAcqStartTime=291,		//			The elapsed time between arming the external start and when the external start signal was received (ms)
					System_DriverVersion=292,		//			The version of the MCA driver
					System_FpgaVersion=293,		//			The version of the FPGA
					Input_TestPulserEnabled=294,		// (0)	Test pulser enabled/disabled
					Input_TestPulserRate=295,		//			Test pulser rate
					Input_TestPulserFrequency=296,		//			Test pulser frequency
					Input_TestPulserAmplitude=297,		// (50.0)	Test pulser amplitude
					Streaming_Port=298,		// (16386)	Streaming port
					Streaming_SessionTimeout=299,		// (600000)	Streaming session timeout
					Streaming_MaximumNumberOfClients=300,		// (10)	Streaming max number of clients
					Streaming_Enable=301,		// (1)	Streaming enabled
					Streaming_Data=302,		// (0)	Streaming data
					Network_Wireless_MAC=303,		//			The MAC address for the wireless ethernet card
					Network_Wired_MAC=304,		//			The MAC address for the wired ethernet card
					Input_ListAcqOptions=305,		// (1)	The acquisition options for list mode
					Input_SCAlld=306,		//			The LLD (%) for the SCAs
					Input_SCAuld=307,		//			The ULD (%)  for the SCA
					Input_SCAbuffer=308,		//			The SCA data buffer
					Input_SCAacqInterval=309,		// (100)	The acquisition interval for the SCAs (ms)
					Input_SCApresetMode=310,		// (1)	The preset options for the SCAs.  See SCApresetMode enumeration
					Input_SCAmode=311,		// (0)	The mode of operation for the SCAs.  See AutomaticManual enumeration.
					Input_SCAstatus=312,		// (0)	The acquisition status for the SCAs.  See CounterStatus enumeration. Write to this parameter to start/stop data acquisition.  Read this parameter to get current acquisition status
					Network_RadnetPort=313,		// (16367)	The socket port for sending Radnet messages on
					Network_RadnetMulticastAddress=314,		// (224.100.0.1)	The Radnet multicast address
					Network_RadnetMulticastTTL=315,		// (5)	The Radnet multicast TTL
					Network_RadnetEnable=316,		// (0)	Enables Radnet messaging.  See OnOff enumeration
					System_StorageOptions=317,		// (0)	Storage options.  See StorageOption enumeration.
					System_StorageMediaState=318,		//			Storage media state.  See StorageMediaState enumeration
					Counter_BufferSize=319,		// (100)	Auxiliary counters maximum buffer size
					Input_SCAbufferSize=320,		// (100)	The SCA buffer size
					Input_MSSbufferSize=321,		// (4)	Maximum size of the MSS buffer
					Input_ActiveGroup=322,		//			The currently acquiring memory group.  This is different than Input_CurrentGroup.  The hardware may dynamically change this value.
					Input_SCAexternalSyncMode=323,		// (0)	The SCA synchronization clock source.  See ClockSource enumeration
					Input_MSSexternalSyncMode=324,		// (0)	MSS synchronization clock source.  See ClockSource enumeration
					Network_RadnetInstrumentID=325,		// (0)	The instrument identifier for RadNet messages
					Network_RadnetInstrumentLocation=326,		// (Default)	The location of the RadNet instrument
					Network_RadnetInput=327,		// (1)	The input number to monitor for RadNet spectroscopy messages
					Network_RadnetEnableBroadcast=328,		// (0)	Enable/disables sending RadNet broadcast messages
#ifndef __EXPOSE_TO_MIDL
				} Code;
#else
				} ParameterCode;
#endif
#ifndef __EXPOSE_TO_MIDL
			}
		}
	}
}
#endif
